export const AdminContants = {
  ALL_USERS_INFO_REQUEST: 'ALL_USERS_INFO_REQUEST',
  ALL_USERS_INFO_SUCCESS: 'ALL_USERS_INFO_SUCCESS',
  ALL_USERS_INFO_FAILURE: 'ALL_USERS_INFO_FAILURE',

  SYSTEM_INFO_REQUEST: 'SYSTEM_INFO_REQUEST',
  SYSTEM_INFO_SUCCESS: 'SYSTEM_INFO_SUCCESS',
  SYSTEM_INFO_FAILURE: 'SYSTEM_INFO_FAILURE',

  CONFIRMED_TRANSACTIONS_REQUEST: 'CONFIRMED_TRANSACTIONS_REQUEST',
  CONFIRMED_TRANSACTIONS_SUCCESS: 'CONFIRMED_TRANSACTIONS_SUCCESS',
  CONFIRMED_TRANSACTIONS_FAILURE: 'CONFIRMED_TRANSACTIONS_FAILURE',

  PENDING_TRANSACTIONS_REQUEST: 'PENDING_TRANSACTIONS_REQUEST',
  PENDING_TRANSACTIONS_SUCCESS: 'PENDING_TRANSACTIONS_SUCCESS',
  PENDING_TRANSACTIONS_FAILURE: 'PENDING_TRANSACTIONS_FAILURE'
};
