export const TransactionContants = {
  ME_REQUEST: "TRANSACTIONS_ME_REQUEST",
  ME_SUCCESS: "TRANSACTIONS_ME_SUCCESS",
  ME_FAILURE: "TRANSACTIONS_ME_FAILURE",

  NEWEST_REQUEST: "TRANSACTIONS_NEWEST_REQUEST",
  NEWEST_SUCCESS: "TRANSACTIONS_NEWEST_SUCCESS",
  NEWEST_FAILURE: "TRANSACTIONS_NEWEST_FAILURE",

  PENDING_REQUEST: "TRANSACTIONS_PENDING_REQUEST",
  PENDING_SUCCESS: "TRANSACTIONS_PENDING_SUCCESS",
  PENDING_FAILURE: "TRANSACTIONS_PENDING_FAILURE",

  DETAIL_REQUEST: "TRANSACTIONS_DETAIL_REQUEST",
  DETAIL_SUCCESS: "TRANSACTIONS_DETAIL_SUCCESS",
  DETAIL_FAILURE: "TRANSACTIONS_DETAIL_FAILURE"
}
