export const UserContants = {
  SIGNUP_REQUEST: 'USER_SIGNUP_REQUEST',
  SIGN_UP_SUCCESS: 'USER_SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'USER_SIGNUP_FAILURE',

  LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

  RESETPASSWORD_REQUEST: 'USER_RESETPASSWORD_REQUEST',
  RESETPASSWORD_SUCCESS: 'USER_RESETPASSWORD_SUCCESS',
  RESETPASSWORD_FAILURE: 'USER_RESETPASSWORD_FAILURE',
  FORGOTPASSWORD_REQUEST: 'USER_FORGOTPASSWORD_REQUEST',
  FORGOTPASSWORD_SUCCESS: 'USER_FORGOTPASSWORD_SUCCESS',
  FORGOTPASSWORD_FAILURE: 'USER_FORGOTPASSWORD_FAILURE',

  OTP_REQUEST: 'USER_OTP_REQUEST',
  OTP_SUCCESS: 'USER_OTP_SUCCESS',
  OTP_FAILURE: 'USER_OTP_FAILURE',

  GET_TFA_CODE_REQUEST: 'GET_TFA_CODE_REQUEST',
  GET_TFA_CODE_SUCCESS: 'GET_TFA_CODE_SUCCESS',
  GET_TFA_CODE_FAILURE: 'GET_TFA_CODE_FAILURE',

  TURN_ON_TFA_REQUEST: 'TURN_ON_TFA_REQUEST',
  TURN_ON_TFA_SUCCESS: 'TURN_ON_TFA_SUCCESS',
  TURN_ON_TFA_FAILURE: 'TURN_ON_TFA_FAILURE',

  AUTHENTICATE_2_STEP_REQUEST: 'AUTHENTICATE_2_STEP_REQUEST',
  AUTHENTICATE_2_STEP_SUCCESS: 'AUTHENTICATE_2_STEP_SUCCESS',
  AUTHENTICATE_2_STEP_FAILURE: 'AUTHENTICATE_2_STEP_FAILURE',
  
  LOGOUT: 'USER_LOGOUT'
};
