export const WalletContants = {
  INFO_REQUEST: "WALLET_INFO_REQUEST",
  INFO_SUCCESS: "WALLET_INFO_SUCCESS",
  INFO_FAILURE: "WALLET_INFO_FAILURE",

  TRANSFER_REQUEST: "TRANSFER_COIN_REQUEST",
  TRANSFER_SUCCESS: "TRANSFER_COIN_SUCCESS",
  TRANSFER_FAILURE: "TRANSFER_COIN_FAILURE"
}
