export const WalletContants = {
  ALL_REQUEST: "TRANSACTIONS_ALL_REQUEST",
  ALL_SUCCESS: "TRANSACTIONS_ALL_SUCCESS",
  ALL_FAILURE: "TRANSACTIONS_ALL_FAILURE",

  NEWEST_REQUEST: "TRANSACTIONS_NEWEST_REQUEST",
  NEWEST_SUCCESS: "TRANSACTIONS_NEWEST_SUCCESS",
  NEWEST_FAILURE: "TRANSACTIONS_NEWEST_FAILURE",


  INFO_REQUEST: "WALLET_INFO_REQUEST",
  INFO_SUCCESS: "WALLET_INFO_SUCCESS",
  INFO_FAILURE: "WALLET_INFO_FAILURE",

  TRANSFER_REQUEST: "TRANSFER_COIN_REQUEST",
  TRANSFER_SUCCESS: "TRANSFER_COIN_SUCCESS",
  TRANSFER_FAILURE: "TRANSFER_COIN_FAILURE"
}
